scalaVersion := "2.13.15"
name := "aoc2024"

libraryDependencies += "org.typelevel" %% "cats-core" % "2.12.0"
libraryDependencies += "org.typelevel" %% "mouse" % "1.3.2"
libraryDependencies += "com.lihaoyi" %% "requests" % "0.9.0"
libraryDependencies += "com.lihaoyi" %% "os-lib" % "0.11.3"
libraryDependencies += "org.scala-lang.modules" %% "scala-parallel-collections" % "1.0.4"
libraryDependencies += "org.scala-lang.modules" %% "scala-parser-combinators" % "2.4.0"
libraryDependencies +=  "com.chuusai" %% "shapeless" % "2.3.12"
libraryDependencies += "org.scalatest" %% "scalatest" % "3.2.19" % Test
libraryDependencies += "com.typesafe.play" %% "play-json" % "2.10.6"
libraryDependencies += "org.scala-graph" %% "graph-core" % "2.0.2"
libraryDependencies += "com.beachape" %% "enumeratum" % "1.7.5"
libraryDependencies += "org.fusesource.jansi" % "jansi" % "1.18"
